"COMPILE/LOAD FILE for BOGGLE
Copyright (C) 1988 Infocom, Inc.  All rights reserved."

<VERSION XZIP>
<SET REDEFINE T>
<FREQUENT-WORDS? <>>
<SHARE-OBJECTS?>

<INSERT-FILE "DEFS">
<INSERT-FILE "Z:CONSTANTS">
<INSERT-FILE "MAIN">
<INSERT-FILE "PLAYER">
<INSERT-FILE "SERVER">
<INSERT-FILE "B">
<INSERT-FILE "DICT">
