<VERSION XZIP>

<SINGLE-FILE? T>

<ROUTINE GO ()
	 <CLEAR -1>
	 <DO-INPUT>>

<ROUTINE DO-INPUT ("AUX" TMP) <REPEAT () <SET TMP <ANA>>>>

<ROUTINE ANA ("AUX" TMP CHR ACHR)
	 <TELL ">">
	 <PRINTN <INPUT 1>>
	 <CRLF>>
