	  	      "BOOT for
		     SAMPLER II
   (c) Copyright 1987 Infocom, Inc.  All Rights Reserved."

<PRINC "
SAMPLER II
">

<FREQUENT-WORDS?>

ON!-INITIAL
OFF!-INITIAL	;"makes debugging possible -- pdl"

;<COND (<GASSIGNED? MUDDLE>
       <GC 0 T 5>
       <BLOAT 90000 0 0 3300 0 0 0 0 0 256>)>

<SET REDEFINE T>

<OR <GASSIGNED? ZILCH>
    <SETG WBREAKS <STRING !\" !,WBREAKS>>>

<COND (<GASSIGNED? ZILCH>
       <ID 0>)>

<SETG NEW-VOC? T>

<INSERT-FILE "MISC" T>
<INSERT-FILE "PARSER" T>
<INSERT-FILE "SYNTAX" T>
<INSERT-FILE "VERBS" T>
<INSERT-FILE "GLOBALS" T>
<INSERT-FILE "WISHBRINGER" T>
<INSERT-FILE "TRINITY" T>
<INSERT-FILE "TOPLEVEL" T>
<INSERT-FILE "ZORK" T>
<INSERT-FILE "LGOP" T>

<PROPDEF SIZE 5>
<PROPDEF CAPACITY 5>
<PROPDEF VALUE 0>
<PROPDEF TVALUE 0>  ;"GROAN. IS THIS TVALUE NECESSARY??"